<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>barcode_gray_256x256.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="barcode_gray_256x256.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="QRCoder" Version="1.7.0" />
    <PackageReference Include="SqlSugarCore" Version="5.1.4.211" />
  </ItemGroup>

</Project>