<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>WebFirst.Services</RootNamespace>
    <AssemblyName>WebFirst.Services</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
         <PackageReference Include="SqlSugarCore" Version="5.1.4.211" />
  </ItemGroup>
  <ItemGroup>
<ProjectReference Include="..\Entites\WebFirst.Entities.csproj" />
</ItemGroup>

</Project>
